#!/bin/bash

# Script to hot-add RAM to a LINUX system using vSphere ESX(i) 4.0

for a in `ls /sys/devices/system/memory/memory*/state`;
do
echo "online" > $a;
done 2>/dev/null;
grep offline /sys/devices/system/memory/memory*/state
